# Generated by Django 2.0.3 on 2018-03-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20180330_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudydata',
            name='date',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
