# Generated by Django 2.0.3 on 2018-03-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20180331_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(default='2018-3-31', max_length=10),
        ),
    ]
